demo/package.json, packages/pintora-diagrams/src/activity/parser/activityDiagram.ne, packages/pintora-diagrams/src/component/parser/componentDiagram.ne, packages/pintora-diagrams/src/sequence/parser/sequenceDiagram.ne, pnpm-lock.yaml
Make them more tolerant to spaces (and the lack of them).  #19
=> Optimize grammar rules

.changeset/tall-donuts-watch.md, packages/pintora-cli/src/cli.ts, packages/pintora-cli/src/render.ts, packages/pintora-core/src/config.ts, packages/pintora-core/src/index.ts, packages/pintora-core/src/type.ts, packages/pintora-diagrams/src/__tests__/test-util.ts, packages/pintora-diagrams/src/activity/artist.ts, packages/pintora-diagrams/src/activity/config.ts, packages/pintora-diagrams/src/component/artist.ts, packages/pintora-diagrams/src/component/config.ts, packages/pintora-diagrams/src/er/__tests__/er-artist.spec.ts, packages/pintora-diagrams/src/er/artist.ts, packages/pintora-diagrams/src/er/config.ts, packages/pintora-diagrams/src/mindmap/artist.ts, packages/pintora-diagrams/src/mindmap/config.ts, packages/pintora-diagrams/src/sequence/__tests__/sequence-artist.spec.ts, packages/pintora-diagrams/src/sequence/artist.ts, packages/pintora-diagrams/src/sequence/config.ts, packages/pintora-diagrams/src/util/artist-util.ts, packages/pintora-diagrams/src/util/config.ts, packages/pintora-renderer/src/renderers/base.ts, packages/pintora-standalone/src/index.ts, pnpm-lock.yaml, website/docs/configuration/config.md, website/docs/getting-started/usage.mdx, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/usage.mdx, website/plugins/docusaurus-theme-pintora/theme/PintoraPlay/PintoraPlay.less
=> feat(pintora-daigrams): support useMaxWidth option for some diagrams

demo/package.json, demo/src/const.ts, demo/src/live-editor/containers/Actions/index.tsx, demo/src/utils/errors.ts, demo/src/utils/filesystem.ts, demo/src/utils/misc.ts, pnpm-lock.yaml
=> feat(demo): save and load code from filesystem

.changeset/famous-lions-yawn.md, .changeset/five-rabbits-retire.md, packages/pintora-diagrams/package.json, packages/pintora-diagrams/src/er/artist.ts, packages/pintora-diagrams/src/er/config.ts, pnpm-lock.yaml
- fix: [er] extend graph bounds with relation edge bounds
- optimize: [er] edges should not intersect
=> fix: [er] extend graph bounds with relation edge bounds

demo/src/live-editor/App.tsx, demo/src/live-editor/containers/EditorSpace/index.tsx, package.json, packages/pintora-cli/package.json, packages/pintora-core/package.json, packages/pintora-diagrams/package.json, packages/pintora-renderer/package.json, packages/pintora-standalone/package.json, pnpm-lock.yaml
- chore: update dev dependencies
- feat(demo): handle `pintora` file drop
=> feat(demo): handle `pintora` file drop

.changeset/tricky-ears-protect.md, .github/workflows/build.yml, demo/cypress/integration/component/component.spec.ts, demo/package.json, packages/pintora-diagrams/src/component/artist.ts, packages/pintora-diagrams/src/component/config.ts, packages/pintora-diagrams/src/util/graph.ts, pnpm-lock.yaml
Fix this layout issue
```
componentDiagram
package "@pintora/renderer" {
() "render()" as renderFn
}
package "@pintora/standalonelllllllllll" {
[standalone]
}
```
=> optimize: [component] pad group node if label is too wide

demo/cypress/integration/er/er.spec.ts, demo/cypress/integration/test-utils/render.ts, demo/live-editor/index.html, demo/preview/index.html, demo/src/pages/preview/main.tsx, packages/pintora-diagrams/src/util/symbols/cloud.ts, packages/pintora-diagrams/src/util/symbols/index.ts
- chore(demo): load google fonts in preview page
- optimize: [component] cloud container
=> optimize: [component] cloud container

.changeset/cool-cobras-agree.md, demo/cypress/integration/test-utils/render.ts, packages/pintora-diagrams/src/er/__tests__/er-parser.spec.js, packages/pintora-diagrams/src/er/artist.ts, packages/pintora-diagrams/src/er/db.ts, packages/pintora-diagrams/src/er/parser/erDiagram.ne, packages/pintora-diagrams/src/gantt/__tests__/__snapshots__/gantt-artist.spec.js.snap, packages/pintora-diagrams/src/gantt/__tests__/gantt-artist.spec.js, packages/pintora-diagrams/src/gantt/artist.ts, packages/pintora-diagrams/src/util/mark-positioner.ts, packages/pintora-diagrams/src/util/number.ts, packages/pintora-diagrams/src/util/text.ts, packages/test-shared/src/data/examples.ts, website/docs/diagrams/er-diagram.mdx
- fix: [er] attribute height bug
=> optimize: [er] can parse attribute comment

.changeset/odd-buckets-compete.md, packages/pintora-diagrams/src/activity/artist.ts, pnpm-lock.yaml
Also assign edge label position to the `labelPoint`
=> optimize: [activity] support ortho edgeType

.changeset/wise-planets-smile.md, packages/pintora-diagrams/scripts/build-grammar.js, packages/pintora-diagrams/src/dot/__tests__/__snapshots__/dot-parser.spec.js.snap, packages/pintora-diagrams/src/dot/__tests__/dot-config.spec.js, packages/pintora-diagrams/src/dot/__tests__/dot-parser.spec.js, packages/pintora-diagrams/src/dot/__tests__/style-context.spec.js, packages/pintora-diagrams/src/dot/artist.ts, packages/pintora-diagrams/src/dot/artist/style-context.ts, packages/pintora-diagrams/src/dot/config.ts, packages/pintora-diagrams/src/dot/db.ts, packages/pintora-diagrams/src/dot/index.ts, packages/pintora-diagrams/src/dot/parser.ts, packages/pintora-diagrams/src/dot/parser/dotDiagram.ne, packages/pintora-diagrams/src/index.ts, packages/pintora-diagrams/src/type.ts, packages/pintora-diagrams/src/util/artist-util.ts, packages/pintora-diagrams/src/util/base-db.ts, packages/pintora-diagrams/src/util/bound.ts, packages/pintora-diagrams/src/util/dagre-wrapper.ts, packages/pintora-diagrams/src/util/parser-shared.ts, packages/test-shared/src/data/examples.ts, pnpm-lock.yaml, tsconfig-build.json, website/docs/configuration/config.md, website/docs/diagrams/dot-diagram.mdx, website/docs/intro.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/intro.md, website/static/data/pintora.tmLanguage.json
=> feat: add dotDiagram

.changeset/new-dots-remember.md, packages/pintora-core/src/themes/theme-default.ts, packages/pintora-diagrams/src/activity/__tests__/__snapshots__/activity-artist.spec.ts.snap, packages/pintora-diagrams/src/component/__tests__/__snapshots__/component-artist.spec.js.snap, packages/pintora-diagrams/src/dot/__tests__/__snapshots__/dot-artist.spec.js.snap, packages/pintora-diagrams/src/dot/__tests__/dot-artist.spec.js, packages/pintora-diagrams/src/dot/artist.ts, packages/pintora-diagrams/src/dot/artist/style-context.ts, packages/pintora-diagrams/src/dot/config.ts, packages/pintora-diagrams/src/dot/db.ts, packages/pintora-diagrams/src/util/arrow/index.ts, packages/pintora-diagrams/src/util/artist-util.ts, packages/pintora-diagrams/src/util/graph.ts, website/docs/diagrams/dot-diagram.mdx
- add arrowhead shape and bg color
- add font family and size
=> feat: [dotDiagram] more attributes; and default theme canvasBackground

.changeset/rich-ravens-carry.md, packages/pintora-diagrams/src/sequence/artist.ts, packages/pintora-diagrams/src/sequence/db.ts
=> fix: [sequence] actor order bug

.changeset/lazy-deers-begin.md, demo/cypress/e2e/dot/dot.spec.ts, demo/cypress/e2e/er/er.spec.ts, packages/pintora-diagrams/src/sequence/__tests__/__snapshots__/sequence-artist.spec.ts.snap, packages/pintora-diagrams/src/sequence/__tests__/sequence-artist.spec.ts, packages/pintora-diagrams/src/sequence/artist.ts, packages/pintora-diagrams/src/util/symbols/diamond.ts, website/docs/diagrams/dot-diagram.mdx
- optimize: [sequence] classifier fallback if there is no symbol icon
- test: [dot] add dotDiagram e2e test
=> optimize: [sequence] classifier fallback if there is no symbol icon

.changeset/red-years-talk.md, demo/cypress/e2e/dot/dot.spec.ts, packages/pintora-diagrams/package.json, packages/pintora-diagrams/src/dot/artist.ts, packages/pintora-diagrams/src/util/bound.ts, pnpm-lock.yaml
=> optimize: dot subgraph should have a min width of its label

packages/pintora-diagrams/src/activity/artist.ts, packages/pintora-diagrams/src/component/artist.ts, packages/pintora-diagrams/src/er/artist.ts, packages/pintora-diagrams/src/mindmap/artist.ts, packages/pintora-diagrams/src/util/graph.ts
- optimize: dagre-wrapper for other diagrams
- optimize: [componentDiagram] subgraph minwidth
=>  optimize: [componentDiagram] subgraph minwidth

.changeset/hot-suits-sing.md, packages/pintora-diagrams/src/dot/__tests__/__snapshots__/dot-artist.spec.js.snap, packages/pintora-diagrams/src/dot/artist.ts, packages/pintora-diagrams/src/dot/artist/const.ts, packages/pintora-diagrams/src/dot/db.ts, website/docs/configuration/config.md, website/docs/diagrams/dot-diagram.mdx
=> optimize: [dotDiagram] edge and node border style

packages/pintora-diagrams/src/__tests__/parser-special-char.spec.ts, packages/pintora-diagrams/src/__tests__/test-util.ts, packages/pintora-diagrams/src/util/parser-shared.ts
Will fix hikerpig/pintora-vscode#5
=> fix: parsing error of '\r\n'

.changeset/olive-tables-jump.md, packages/pintora-cli/src/__tests__/render-cases.spec.ts, packages/pintora-cli/src/const.ts, packages/pintora-cli/src/render.ts, packages/pintora-cli/tsconfig.json, packages/pintora-core/src/util/util.ts, packages/pintora-diagrams/src/sequence/__tests__/__snapshots__/sequence-artist.spec.ts.snap, packages/pintora-diagrams/src/sequence/artist/loop.ts
=> fix(cli): ReferenceError: CanvasPattern is not defined

.changeset/stale-plums-happen.md, demo/cypress/e2e/sequence/sequence.spec.ts, packages/pintora-diagrams/src/sequence/artist.ts, packages/pintora-diagrams/src/sequence/artist/loop.ts
=> fix: [sequenceDiagram] excessive box width bug

pnpm-lock.yaml, website/package.json
=> Revert "fix(deps): update dependency @mdx-js/react to v3"

.changeset/young-waves-whisper.md, demo/package.json, demo/src/pages/highlight/main.tsx, pnpm-lock.yaml, website/package.json, website/plugins/docusaurus-theme-pintora/theme/PintoraPlay/highlight.ts
- fix(deps): update dependency shiki to ^0.14.0
- fix(website): fix broken highlight
=> fix website broken highlight

.changeset/long-experts-brake.md, packages/pintora-diagrams/src/activity/__tests__/__snapshots__/activity-artist.spec.ts.snap, packages/pintora-diagrams/src/activity/__tests__/activity-parser.spec.js, packages/pintora-diagrams/src/activity/artist.ts, packages/pintora-diagrams/src/activity/db.ts
=> fix: [activity] Incorrect display for nested group

.changeset/ninety-trainers-occur.md, packages/pintora-diagrams/src/component/artist.ts, packages/pintora-diagrams/src/component/config.ts, pnpm-lock.yaml, website/docs/configuration/config.md
=> feat: [componentDiagram] Add a param 'hideGroupType'

.changeset/rude-wasps-wait.md, packages/pintora-diagrams/src/mindmap/__tests__/mindmap-parser.spec.js, packages/pintora-diagrams/src/mindmap/parser/mindmap.ne
=> fix: [mindmap] hyphen inside multiline text

.changeset/unlucky-geckos-tap.md, packages/pintora-core/src/util/geometry.ts, packages/pintora-core/src/util/text-metric.ts, packages/pintora-diagrams/scripts/build-grammar.js, packages/pintora-diagrams/src/class/__tests__/__snapshots__/class-parser.spec.ts.snap, packages/pintora-diagrams/src/class/__tests__/class-parser.spec.ts, packages/pintora-diagrams/src/class/artist.ts, packages/pintora-diagrams/src/class/config.ts, packages/pintora-diagrams/src/class/db.ts, packages/pintora-diagrams/src/class/index.ts, packages/pintora-diagrams/src/class/parser.ts, packages/pintora-diagrams/src/class/parser/classDiagram.ne, packages/pintora-diagrams/src/index.ts, packages/pintora-diagrams/src/util/arrow/index.ts, packages/pintora-diagrams/src/util/graph.ts, packages/pintora-diagrams/src/util/line-util.ts, packages/pintora-diagrams/src/util/mark-positioner.ts, packages/pintora-diagrams/src/util/parser-shared.ts, packages/pintora-renderer/src/renderers/SvgRenderer.ts, packages/pintora-renderer/src/renderers/base.ts, packages/test-shared/src/data/examples.ts, pnpm-lock.yaml, website/docs/diagrams/class-diagram.mdx
=> feat: [classDiagram] initial commit

.changeset/fair-houses-beg.md, .changeset/stupid-nails-scream.md, packages/pintora-diagrams/src/activity/__tests__/activity-parser.spec.js, packages/pintora-diagrams/src/activity/parser/activityDiagram.ne, packages/pintora-diagrams/src/class/__tests__/__snapshots__/class-parser.spec.ts.snap, packages/pintora-diagrams/src/class/__tests__/class-parser.spec.ts, packages/pintora-diagrams/src/class/artist.ts, packages/pintora-diagrams/src/class/config.ts, packages/pintora-diagrams/src/class/db.ts, packages/pintora-diagrams/src/class/parser/classDiagram.ne, packages/pintora-diagrams/src/dot/parser/dotDiagram.ne, packages/pintora-diagrams/src/er/__tests__/er-parser.spec.js, packages/pintora-diagrams/src/sequence/__tests__/__snapshots__/sequence-artist.spec.ts.snap, packages/pintora-diagrams/src/sequence/__tests__/sequence-parser.spec.js, packages/pintora-diagrams/src/sequence/artist.ts, packages/pintora-diagrams/src/sequence/db.ts, packages/pintora-diagrams/src/sequence/parser/sequenceDiagram.ne, packages/test-shared/src/data/examples.ts
- feat!: support more characters inside multiline notes
- feat: [classDiagram] add note
=> feat!: support more characters inside multiline notes

.changeset/bright-boats-walk.md, demo/cypress/e2e/activity/activity.spec.ts, packages/pintora-diagrams/src/activity/__tests__/activity-artist.spec.ts, packages/pintora-diagrams/src/activity/artist.ts, packages/pintora-diagrams/src/sequence/artist.ts
=> feat(diagrams): [activity] Should draw a no-action-line when there is no else block

.changeset/modern-buckets-float.md, packages/pintora-diagrams/src/sequence/artist.ts
Related https://github.com/hikerpig/pintora-vscode/issues/8
=> fix nested loop container bg rect drawing order

.changeset/forty-hotels-retire.md, packages/pintora-diagrams/src/activity/__tests__/__snapshots__/activity-artist.spec.ts.snap, packages/pintora-diagrams/src/activity/artist.ts
=> fix: [activityDiagram] wrong condition else label

.changeset/short-tomatoes-joke.md, packages/pintora-diagrams/src/sequence/artist.ts, packages/pintora-diagrams/src/sequence/config.ts, website/docs/configuration/config.md
=> feat: [sequence] add `participantBorderColor` param

.changeset/shaggy-readers-scream.md, demo/cypress/e2e/activity/activity.spec.ts, packages/pintora-diagrams/src/activity/artist.ts
=> fix: [activity] strange corner whene condition is inside while

packages/pintora-cli/package.json, packages/pintora-cli/src/__tests__/render-cases.spec.ts, packages/pintora-cli/src/cli.ts, pnpm-lock.yaml
Update canvas version to use @pintora/cli on Windows 11
=> Bump canvas to v3.0.1 and update packages

.changeset/seven-buses-chew.md, packages/pintora-diagrams/shared-grammars/config.ne, packages/pintora-diagrams/src/mindmap/__tests__/mindmap-parser.spec.js, packages/pintora-diagrams/src/mindmap/parser/mindmap.ne
=> fix(diagrams): [mindmap] parsing error when `@param` comes with value with space
